image: python:latest

pages:
  tags:
  - shared
  before_script:
  - apt-get update
  - apt-get install -y nodejs-dev bundler
  - make develop
  script: 
  - make public
  artifacts:
    paths:
    - public/
